# Generated by Django 4.2.1 on 2023-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_genero_persona_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='persona',
        ),
        migrations.AddField(
            model_name='mascota',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
