# Generated by Django 4.2.1 on 2023-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_mascota_persona_mascota_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
